config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
  root 'welcome#home'

  get 'about' => 'welcome#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord

  extend FriendlyId
  friendly_id :titolo, use: :slugged

	belongs_to :user
  has_many :sales

	has_attached_file :cover
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/,
  	message: "Solo le immagini supportate"

  	has_attached_file :allegato
  	validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ], 
  	message: "Formato non suportato"

  	validates :titolo, :descrizione, :prezzo, presence: true
  	validates :prezzo, numericality: { greater_than: 49 }
  	validates :cover, attachment_presence: true
  	validates :allegato, attachment_presence: true

end

app/models/sale.rb
class Sale < ApplicationRecord
	before_create :generate_guid
	belongs_to :content

	private 
		def generate_guid
			self.guid = SecureRandom.uuid()
		end 
	end
end

app/models/user.rb
class User < ApplicationRecord

  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  	has_many :contents

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :control_user, only: [:edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = current_user.contents.build
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.friendly.find(params[:id])    
    end
    def control_user
      if current_user != @content.user 
        redirect_to root_url, alert:"Lei non ha accesso a questo articolo, perchè non la creato lei!"
      end 
    end 


    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :prezzo, :cover, :allegato)
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contents/_form.html.erb
<%= form_for content, html: { multipart: true } do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="grey-text">Aggiungi qui il tuo allegato:</label><br>
    <%= f.file_field :allegato %>
  </div><br>

  <div class="field">
    <%= f.label :titolo %>
    <%= f.text_field :titolo %>
  </div>

  <div class="field">
    <%= f.label :descrizione %>
    <%= f.text_area :descrizione, class: "materialize-textarea" %>
  </div>

  <div class="field">
    <%= f.label :prezzo_min_50_cent %>
    <%= f.text_field :prezzo %>
  </div>

  <div class="field">
    <label class="grey-text">Aggiungi qui la foto di copertina:</label><br>
    <%= f.file_field :cover %>
  </div><br>

  <div class="actions">
    <%= f.submit 'Salva contenuto', class: "btn btn-form" %>
  </div><br>
<% end %>

app/views/contents/edit.html.erb
<h1 class="center">Modifica contenuto</h1>

<%= render 'form', content: @content %>

<%= link_to 'Mostra ', @content %> |
<%= link_to 'Indietro', contents_path %>

app/views/contents/index.html.erb
<!--<h1>Contenuti</h1>-->
<div class="row">
  <% @contents.each do |content| %>
    <div class="col s3">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag content.cover.url, class: "activator" %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">more_vert</i></span>
          <div>
            <span>Venduto da:<p class="right"><%= content.user.name %></p>         
            </span>
            <span>Prezzo prodotto: 
              <p class="right"><%= number_to_currency(content.prezzo) %></p>
            </span>
          </div>
          <br>
          <div>
              <P class="center"><%= link_to 'Mostra', content, class: "btn" %></P>
            <% if current_user == content.user%>
            <br>
            <div class="center"
              <p><%= link_to 'Modifica', edit_content_path(content) %>
              <%= link_to 'Elimina', content, method: :delete, data: { confirm: 'Are you sure?' } %></p>
              </div>
            <% end %>
          </div>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">close</i></span>
          <p><%= content.descrizione %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<div class = "center">
  <%= will_paginate @contents %>
</div><br>

app/views/contents/new.html.erb
<h1 class="center">Aggiungi contenuto</h1>

<%= render 'form', content: @content %>

<%= link_to 'Indietro', contents_path %>

app/views/contents/show.html.erb
<div class="row">
	<div class="col l6">
			<%= image_tag @content.cover.url, class: "responsive-img show-img" %>
	</div>
	<div class="col l6">
		<h1 class="gradino-titolo"><%= @content.titolo %></h1>

		<p class= "show-prezzo">Prezzo prodotto: <%= number_to_currency(@content.prezzo) %></p>

		<p>Venduto da: <%= @content.user.name %></p>

		<p><%= @content.descrizione %></p>
	</div>

</div>

<% if current_user == @content.user %> 
<%= link_to 'Modifica ', edit_content_path(@content) %> 
<% end %>
<%= link_to 'Indietro ', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer #00695c teal darken-3">
  <div class="footer-copyright">
      <div class="container">
        <div class="row">
          <div class="col s4">
            @2017 Vapiano.com
          </div>
          <div class="col s4">
            Social media
          </div>
          <div class="col s4">
          <%= link_to "About", about_path, class: "grey-text text-lighten-4 right" %>
          </div>
        </div>
      </div>
  </div>
</footer>
            

app/views/layouts/_header.html.erb
<header class= "navbar-fixed">
    <ul id="dropdown1" class="dropdown-content">
      <li><%= link_to 'Vendi contenuto', new_content_path %></li>
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Esci", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Iscriviti", new_user_registration_path %></li>
        <li><%= link_to "Accedi", new_user_session_path %></li>    
      <% end %>

      <li class="divider"></li>

    </ul>
    <nav class="#00695c teal darken-3">
      <div class="nav-wrapper container">
        <%= link_to "Vapiano", root_path, class: "brand-logo" %>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to 'Vendi contenuto', new_content_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Esci", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Iscriviti", new_user_registration_path %></li>
            <li><%= link_to "Accedi", new_user_session_path %></li>
          <% end %>
          
          <!-- Dropdown Trigger -->
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vapiano</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container margine">
      <% flash.each do |type, message| %>
      <script>
        Materialize.toast('<%= message %>', 4000)
      </script>
      <% end %> 
    </div>
    <main class="container">
    <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>

    <script>
    $(".dropdown-button").dropdown();
    </script>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>